import type { SessionInfo, RawMessage } from "./types";

// ── Sessions ───────────────────────────────────────────────────────────────

export const MOCK_SESSIONS: SessionInfo[] = [
  {
    id: "main-fleet",
    workspacePath: "/Users/dev/projects/fleet",
    workspaceName: "claw-fleet",
    ideName: "VS Code",
    isSubagent: false,
    parentSessionId: null,
    agentType: null,
    agentDescription: null,
    slug: null,
    aiTitle: "Implement mobile QR pairing",
    status: "delegating",
    tokenSpeed: 42.3,
    totalOutputTokens: 125000,
    lastMessagePreview: "I'll update the embedded server to handle the QR code endpoint and add CORS headers...",
    lastActivityMs: Date.now() - 3000,
    createdAtMs: Date.now() - 3600000,
    jsonlPath: "/mock/fleet-main.jsonl",
    model: "claude-sonnet-4-20250514",
    thinkingLevel: null,
    pid: 12345,
    pidPrecise: true,
    lastSkill: null,
    contextPercent: 45,
    agentSource: "claude-code",
  },
  {
    id: "sub-fleet-explore",
    workspacePath: "/Users/dev/projects/fleet",
    workspaceName: "claw-fleet",
    ideName: "VS Code",
    isSubagent: true,
    parentSessionId: "main-fleet",
    agentType: "explore",
    agentDescription: "Research SSE polyfills for React Native",
    slug: "explore-sse-polyfills",
    aiTitle: null,
    status: "executing",
    tokenSpeed: 18.7,
    totalOutputTokens: 8200,
    lastMessagePreview: "Searching node_modules for EventSource implementations...",
    lastActivityMs: Date.now() - 1000,
    createdAtMs: Date.now() - 600000,
    jsonlPath: "/mock/fleet-sub-explore.jsonl",
    model: "claude-haiku-4-20250414",
    thinkingLevel: null,
    pid: 12346,
    pidPrecise: true,
    lastSkill: null,
    contextPercent: 12,
    agentSource: "claude-code",
  },
  {
    id: "sub-fleet-plan",
    workspacePath: "/Users/dev/projects/fleet",
    workspaceName: "claw-fleet",
    ideName: "VS Code",
    isSubagent: true,
    parentSessionId: "main-fleet",
    agentType: "plan",
    agentDescription: "Design embedded HTTP server architecture",
    slug: null,
    aiTitle: null,
    status: "idle",
    tokenSpeed: 0,
    totalOutputTokens: 4100,
    lastMessagePreview: "Plan completed. 5 steps identified.",
    lastActivityMs: Date.now() - 900000,
    createdAtMs: Date.now() - 1200000,
    jsonlPath: "/mock/fleet-sub-plan.jsonl",
    model: "claude-sonnet-4-20250514",
    thinkingLevel: null,
    pid: null,
    pidPrecise: false,
    lastSkill: null,
    contextPercent: null,
    agentSource: "claude-code",
  },
  {
    id: "main-webapp",
    workspacePath: "/Users/dev/projects/webapp",
    workspaceName: "my-webapp",
    ideName: "Cursor",
    isSubagent: false,
    parentSessionId: null,
    agentType: null,
    agentDescription: null,
    slug: "fix-auth-redirect",
    aiTitle: "Fix OAuth redirect loop",
    status: "streaming",
    tokenSpeed: 65.1,
    totalOutputTokens: 340000,
    lastMessagePreview: "The issue is in the middleware — it checks auth state before the callback route is registered...",
    lastActivityMs: Date.now() - 500,
    createdAtMs: Date.now() - 7200000,
    jsonlPath: "/mock/webapp-main.jsonl",
    model: "claude-opus-4-20250514",
    thinkingLevel: "high",
    pid: 12347,
    pidPrecise: true,
    lastSkill: null,
    contextPercent: 82,
    agentSource: "cursor",
  },
  {
    id: "main-api",
    workspacePath: "/Users/dev/projects/api",
    workspaceName: "backend-api",
    ideName: null,
    isSubagent: false,
    parentSessionId: null,
    agentType: null,
    agentDescription: null,
    slug: null,
    aiTitle: "Add rate limiting middleware",
    status: "waitingInput",
    tokenSpeed: 0,
    totalOutputTokens: 52000,
    lastMessagePreview: "I've implemented the token bucket algorithm. Should I use Redis or in-memory storage?",
    lastActivityMs: Date.now() - 120000,
    createdAtMs: Date.now() - 5400000,
    jsonlPath: "/mock/api-main.jsonl",
    model: "claude-sonnet-4-20250514",
    thinkingLevel: null,
    pid: 12348,
    pidPrecise: true,
    lastSkill: null,
    contextPercent: 35,
    agentSource: "claude-code",
  },
  {
    id: "main-docs",
    workspacePath: "/Users/dev/projects/docs",
    workspaceName: "documentation",
    ideName: null,
    isSubagent: false,
    parentSessionId: null,
    agentType: null,
    agentDescription: null,
    slug: null,
    aiTitle: null,
    status: "idle",
    tokenSpeed: 0,
    totalOutputTokens: 15000,
    lastMessagePreview: "Documentation updated successfully.",
    lastActivityMs: Date.now() - 3600000,
    createdAtMs: Date.now() - 86400000,
    jsonlPath: "/mock/docs-main.jsonl",
    model: "claude-haiku-4-20250414",
    thinkingLevel: null,
    pid: null,
    pidPrecise: false,
    lastSkill: null,
    contextPercent: null,
    agentSource: "claude-code",
  },
];

// ── Messages per session ───────────────────────────────────────────────────

const MESSAGES_FLEET_MAIN: RawMessage[] = [
  {
    type: "user", uuid: "fm-1",
    timestamp: new Date(Date.now() - 300000).toISOString(),
    message: { role: "user", content: "Implement mobile QR pairing for the Claw Fleet app. Desktop should show a QR code that mobile scans to connect." },
  },
  {
    type: "assistant", uuid: "fm-2",
    timestamp: new Date(Date.now() - 295000).toISOString(),
    message: {
      role: "assistant", model: "claude-sonnet-4-20250514",
      content: [
        { type: "thinking", thinking: "The user wants mobile QR pairing. I need to:\n1. Add an embedded HTTP server to the desktop app\n2. Integrate cloudflared for tunnel\n3. Generate QR code with tunnel URL + auth token\n4. Mobile app scans and connects via the tunnel" },
        { type: "text", text: "I'll implement this in several steps. First, let me explore the existing server architecture." },
        { type: "tool_use", id: "t1", name: "Read", input: { file_path: "src-tauri/src/lib.rs" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 2100, output_tokens: 280 },
    },
  },
  {
    type: "assistant", uuid: "fm-3",
    timestamp: new Date(Date.now() - 290000).toISOString(),
    message: {
      role: "assistant", model: "claude-sonnet-4-20250514",
      content: [
        { type: "tool_result", tool_use_id: "t1", content: "pub struct AppState {\n    pub backend: Arc<RwLock<Box<dyn Backend>>>,\n    pub locale: Arc<Mutex<String>>,\n    // ... 780 more lines" },
        { type: "text", text: "I can see the `AppState` structure. I'll add the embedded server and tunnel modules. Let me delegate the architecture research to a subagent." },
        { type: "tool_use", id: "t2", name: "Agent", input: { description: "Research SSE polyfills", prompt: "Find SSE polyfills compatible with React Native" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 3500, output_tokens: 420 },
    },
  },
];

const MESSAGES_FLEET_SUB_EXPLORE: RawMessage[] = [
  {
    type: "assistant", uuid: "fse-1",
    timestamp: new Date(Date.now() - 280000).toISOString(),
    message: {
      role: "assistant", model: "claude-haiku-4-20250414",
      content: [
        { type: "text", text: "Searching for SSE polyfills compatible with React Native (Hermes engine)." },
        { type: "tool_use", id: "e1", name: "Bash", input: { command: "npm search react-native-sse --json | head -20" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 500, output_tokens: 120 },
    },
  },
  {
    type: "assistant", uuid: "fse-2",
    timestamp: new Date(Date.now() - 275000).toISOString(),
    message: {
      role: "assistant", model: "claude-haiku-4-20250414",
      content: [
        { type: "tool_result", tool_use_id: "e1", content: "[\n  { \"name\": \"react-native-sse\", \"version\": \"1.2.1\", \"description\": \"EventSource polyfill for React Native using XMLHttpRequest\" }\n]" },
        { type: "text", text: "Found `react-native-sse` — it implements EventSource using XMLHttpRequest (available in Hermes). This is the best option:\n\n- Uses XMLHttpRequest under the hood (works in RN)\n- Supports custom event names via `addEventListener`\n- Handles reconnection automatically\n\n**Recommendation:** Install `react-native-sse` and use it as a drop-in replacement for the browser's `EventSource` API." },
      ],
      stop_reason: "end_turn",
      usage: { input_tokens: 800, output_tokens: 250 },
    },
  },
];

const MESSAGES_WEBAPP: RawMessage[] = [
  {
    type: "user", uuid: "wa-1",
    timestamp: new Date(Date.now() - 200000).toISOString(),
    message: { role: "user", content: "Fix the login page — users are getting a blank white screen after OAuth redirect on mobile browsers." },
  },
  {
    type: "assistant", uuid: "wa-2",
    timestamp: new Date(Date.now() - 195000).toISOString(),
    message: {
      role: "assistant", model: "claude-opus-4-20250514",
      content: [
        { type: "thinking", thinking: "OAuth redirect blank screen on mobile. Common causes:\n1. Callback route blocked by auth middleware\n2. SameSite cookie issues on mobile Safari\n3. Fragment (#) in redirect URLs" },
        { type: "text", text: "I'll investigate the OAuth redirect flow. The most likely causes on mobile are:\n1. **Route ordering** — callback route vs auth middleware\n2. **Cookie issues** — `SameSite` attribute on mobile Safari\n3. **Fragment handling** — `#` in redirect URLs" },
        { type: "tool_use", id: "w1", name: "Read", input: { file_path: "src/middleware/auth.ts" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 1250, output_tokens: 340 },
    },
  },
  {
    type: "assistant", uuid: "wa-3",
    timestamp: new Date(Date.now() - 190000).toISOString(),
    message: {
      role: "assistant", model: "claude-opus-4-20250514",
      content: [
        { type: "tool_result", tool_use_id: "w1", content: "1  import { NextRequest, NextResponse } from 'next/server';\n2  \n3  export function middleware(request: NextRequest) {\n4    const session = request.cookies.get('session');\n5    if (!session && !request.nextUrl.pathname.startsWith('/api/auth')) {\n6      return NextResponse.redirect(new URL('/login', request.url));\n7    }\n8  }" },
        { type: "text", text: "Found it! The middleware on **line 5** checks for `/api/auth` but the OAuth callback is at `/auth/callback`. Mobile browsers hit this redirect loop:\n\n```\n/auth/callback → middleware sees no session → /login → OAuth → /auth/callback → ...\n```" },
        { type: "tool_use", id: "w2", name: "Edit", input: { file_path: "src/middleware/auth.ts", old_string: "!request.nextUrl.pathname.startsWith('/api/auth')", new_string: "!request.nextUrl.pathname.startsWith('/api/auth') && !request.nextUrl.pathname.startsWith('/auth/')" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 2100, output_tokens: 520 },
    },
  },
  {
    type: "assistant", uuid: "wa-4",
    timestamp: new Date(Date.now() - 180000).toISOString(),
    message: {
      role: "assistant", model: "claude-opus-4-20250514",
      content: [
        { type: "tool_result", tool_use_id: "w2", content: "File edited successfully." },
        { type: "tool_use", id: "w3", name: "Bash", input: { command: "npm run build && npm test -- --grep 'auth'" } },
      ],
      stop_reason: "tool_use",
      usage: { input_tokens: 2400, output_tokens: 90 },
    },
  },
  {
    type: "assistant", uuid: "wa-5",
    timestamp: new Date(Date.now() - 170000).toISOString(),
    message: {
      role: "assistant", model: "claude-opus-4-20250514",
      content: [
        { type: "tool_result", tool_use_id: "w3", content: "Build completed successfully.\n\n  PASS  tests/auth.test.ts\n    ✓ redirects unauthenticated users to login (45ms)\n    ✓ allows access to auth callback route (12ms)\n    ✓ sets session cookie with correct attributes (28ms)\n\n  3 passing (85ms)" },
        { type: "text", text: "All tests pass.\n\n## Changes Made\n\n1. **`src/middleware/auth.ts`** — Added `/auth/` path to the middleware exclusion list\n\n## Root Cause\n\nThe auth middleware blocked `/auth/callback`, causing an infinite redirect loop on mobile." },
      ],
      stop_reason: "end_turn",
      usage: { input_tokens: 3200, output_tokens: 450 },
    },
  },
];

const MESSAGES_API: RawMessage[] = [
  {
    type: "user", uuid: "api-1",
    timestamp: new Date(Date.now() - 500000).toISOString(),
    message: { role: "user", content: "Add rate limiting to the API. Use a token bucket algorithm." },
  },
  {
    type: "assistant", uuid: "api-2",
    timestamp: new Date(Date.now() - 495000).toISOString(),
    message: {
      role: "assistant", model: "claude-sonnet-4-20250514",
      content: [
        { type: "text", text: "I'll implement rate limiting using a token bucket algorithm. Before I proceed — should I use **Redis** (distributed, works across instances) or **in-memory** (simpler, single-instance only) for storing the bucket state?" },
      ],
      stop_reason: "end_turn",
      usage: { input_tokens: 800, output_tokens: 150 },
    },
  },
];

const MESSAGES_MAP: Record<string, RawMessage[]> = {
  "/mock/fleet-main.jsonl": MESSAGES_FLEET_MAIN,
  "/mock/fleet-sub-explore.jsonl": MESSAGES_FLEET_SUB_EXPLORE,
  "/mock/fleet-sub-plan.jsonl": [],
  "/mock/webapp-main.jsonl": MESSAGES_WEBAPP,
  "/mock/api-main.jsonl": MESSAGES_API,
  "/mock/docs-main.jsonl": [],
};

export { MESSAGES_MAP };
